### ISSUE TITLE
Switch to dbus LVM2 interface

### ISSUE THREAD

**Issue by MOZGIII** [open-iscsi/targetd#25]
Python bindings are deprecated, so this project should switch to dbus to work with LVM.

**Comment by j-griffith** [comment]
@agrover I was wondering if there was any thing going on around this?  I'm not familiar with the dbus implementation for this but would be interested in helping out to see things updated.  I've got one project that is using targetd and needs updated and another potential good use for targetd so I'm willing to help out but would need some pointers on how to use dbus etc.

**Comment by tasleson** [comment]
@j-griffith There is some outdated documentation on the dbus interface here:  https://github.com/tasleson/lvm-dubstep/blob/master/api.md  However, the interface supports introspection so you can leverage tools like d-feet and snoop around with it.  I will try to update that documentation, but that really should be documented in upstream lvm repo now.  Libblkdev is using lvm dbus, ref. https://github.com/storaged-project/libblockdev/blob/master/src/plugins/lvm-dbus.c

As for targetd utilizing lvm dbus, that's only part of the story.  Even with those bits re-written, targetd is utilizing btrfs for the remote FS API portion.  Btrfs has been deprecated in RHEL: ref. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.4_release_notes/chap-red_hat_enterprise_linux-7.4_release_notes-deprecated_functionality  so that would need to be moved over to something else potentially too, to continue to work on RHEL.

We've deprecated targetd in Fedora for the above reasons and the fact that we didn't get much uptake.  I'll discuss with @agrover about putting a blurb about that on the main project page.  If however, we get some big patches and renewed community support for targetd, it could certainly be brought back.

**Comment by j-griffith** [comment]
@tasleson ack, thanks for all the good info

**Comment by MOZGIII** [comment]
So, it seems like it doesn't make sense to fix it in targetd. Is there any alternative to targetd that still works with LVM?

**Comment by tasleson** [comment]
Addressed with #27
